apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Values.job.metadata.name}}
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: {{.Values.job.metadata.name}}
          image: busybox
          command: ["sh", "-c", "echo ${MESSAGE}"]
          env:
            - 
              name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: message
            - 
              name: {{.Values.secret.metadata.name}}
              valueFrom:
                secretKeyRef:
                  name: {{.Values.secret.metadata.name}}
                  key: password