name: CI Pipeline

on:
  push:
    branches:
      - dev

env:
  PYTHON_VERSION: "3.11.14"
  APP_PATH: "./Final Project/app/backend"

jobs:
  build:
    runs-on: ${{ vars.FINAL_PROJECT_BASE_IMAGE }}
    steps:

      -
        name: Display variables
        run: |
          echo "BASE_IMAGE: ${{ vars.FINAL_PROJECT_BASE_IMAGE }}"
          echo "PYTHON_VERSION: ${{ env.PYTHON_VERSION }}"
          echo "APP_PATH: ${{ env.APP_PATH }}"

      - 
        name: Checkout repository branch
        uses: actions/checkout@v4

      - 
        name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      -
        name: Install dependencies
        run: pip install -r ${{ env.APP_PATH }}/requirements.txt

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Build and Push image
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.APP_PATH }}
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/final-project-backend:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha,scope=${{ runner.os }}-buildx
          cache-to: type=gha,scope=${{ runner.os }}-buildx-new,mode=max